Fix data race between AddModuleLevel and GetLevel
holoplot/go-logging pull request #1
Opened 2020-05-15 08:17 UTC by Asalle

2020-05-15 08:33 UTC, zonque requested changes
Given that this is potential upstream material (as we can't afford the maintenance burden of a fork off this package), you need to explain where exactly the race is and also provide a commit log that justifies your change.

2020-05-15 08:44 UTC, Asalle commented
I'm in the process of testing it, will prepare a proper commit message as soon as it works

2020-05-18 08:48 UTC, zonque commented
> If not locked, this results in race:
> 
>     1. backend.go:27 - reassigning the global variable (write)
> 
>     2. logger.go:141 - accessing a default variable (read)

For the upstream PR, I suggest you quote some code here and name the variables by name. This will enable readers to comprehend things after the merge, when line numbers might have changed etc.

2020-05-18 09:56 UTC, Asalle commented
created a pr in upstream, closing this one
we'll use another fix

2020-05-18 09:56 UTC, closed without merging